import { Media } from "@/types";
import { Brand, Category, Product } from "@/types/product";

export const mockBrands: Brand[] = [
  {
    id: 1,
    name: "مهرآسا",
    logo: "/mock/image_32.jpg",
  },
  {
    id: 2,
    name: "عطر نیک",
    logo: "/mock/image_33.jpg",
  },
  {
    id: 3,
    name: "تسبیح‌کو",
    logo: "/mock/image_25.jpg",
  },
  {
    id: 4,
    name: "کتاب دعا",
    logo: "/mock/image_36.jpg",
  },
  {
    id: 5,
    name: "چراغین",
    logo: "/mock/image_50.jpg",
  },
  {
    id: 6,
    name: "دیجیتال‌پلاس",
    logo: "/mock/image_44.jpg",
  },
  {
    id: 7,
    name: "ماگ‌لند",
    logo: "/mock/image_49.jpg",
  },
  {
    id: 8,
    name: "اسپیکر‌استار",
    logo: "/mock/image_53.jpg",
  },
];

export const categories: Category[] = [
  {
    id: 1,
    title: "ادعیه و کتب مذهبی",
    slug: "prayers-books",
    discount: "10%",
    level: 1,
    media: {
      id: 1001,
      url: "/mock/image_3.jpg",
      type: "image",
      alt_text: "تصویر محصول ادعیه و کتب مذهبی",
      product_id: null,
      category_id: null,
      user_id: null,
      created_at: "2025-09-06T10:37:27.736Z",
      media: null,
    },
    children: [
      {
        id: 11,
        title: "کتاب دعا",
        slug: "prayers-books-sub1",
        discount: "0",
        level: 2,
        children: [
          {
            id: 111,
            title: "کتاب دعا - زیرگروه 1",
            slug: "prayers-books-sub1-child1",
            discount: "0",
            level: 3,
            parent: {
              id: 11,
              title: "کتاب دعا",
              slug: "prayers-books-sub1",
              level: 2,
              parent: {
                id: 1,
                title: "ادعیه و کتب مذهبی",
                slug: "prayers-books",
                level: 1,
                parent: null,
                parent_id: 1,
                discount: "10%",
              },
              parent_id: 11,
              discount: "0",
            },
            parent_id: 11,
            children: [],
          },
          {
            id: 112,
            title: "کتاب دعا - زیرگروه 2",
            slug: "prayers-books-sub1-child2",
            discount: "0",
            level: 3,
            parent: {
              id: 11,
              title: "کتاب دعا",
              slug: "prayers-books-sub1",
              level: 2,
              parent: {
                id: 1,
                title: "ادعیه و کتب مذهبی",
                slug: "prayers-books",
                level: 1,
                parent: null,
                parent_id: 1,
                discount: "10%",
              },
              parent_id: 11,
              discount: "0",
            },
            parent_id: 11,
            children: [],
          },
        ],
        parent: {
          id: 1,
          title: "ادعیه و کتب مذهبی",
          slug: "prayers-books",
          level: 1,
          parent: null,
          parent_id: 1,
          discount: "10%",
        },
        parent_id: 1,
      },
      {
        id: 12,
        title: "ادعیه جیبی",
        slug: "prayers-books-sub2",
        discount: "0",
        level: 2,
        children: [
          {
            id: 121,
            title: "ادعیه جیبی - زیرگروه 1",
            slug: "prayers-books-sub2-child1",
            discount: "0",
            level: 3,
            parent: {
              id: 12,
              title: "ادعیه جیبی",
              slug: "prayers-books-sub2",
              level: 2,
              parent: {
                id: 1,
                title: "ادعیه و کتب مذهبی",
                slug: "prayers-books",
                level: 1,
                parent: null,
                parent_id: 1,
                discount: "10%",
              },
              parent_id: 12,
              discount: "0",
            },
            parent_id: 12,
            children: [],
          },
          {
            id: 122,
            title: "ادعیه جیبی - زیرگروه 2",
            slug: "prayers-books-sub2-child2",
            discount: "0",
            level: 3,
            parent: {
              id: 12,
              title: "ادعیه جیبی",
              slug: "prayers-books-sub2",
              level: 2,
              parent: {
                id: 1,
                title: "ادعیه و کتب مذهبی",
                slug: "prayers-books",
                level: 1,
                parent: null,
                parent_id: 1,
                discount: "10%",
              },
              parent_id: 12,
              discount: "0",
            },
            parent_id: 12,
            children: [],
          },
        ],
        parent: {
          id: 1,
          title: "ادعیه و کتب مذهبی",
          slug: "prayers-books",
          level: 1,
          parent: null,
          parent_id: 1,
          discount: "10%",
        },
        parent_id: 1,
      },
      {
        id: 13,
        title: "قرآن",
        slug: "prayers-books-sub3",
        discount: "0",
        level: 2,
        children: [
          {
            id: 131,
            title: "قرآن - زیرگروه 1",
            slug: "prayers-books-sub3-child1",
            discount: "0",
            level: 3,
            parent: {
              id: 13,
              title: "قرآن",
              slug: "prayers-books-sub3",
              level: 2,
              parent: {
                id: 1,
                title: "ادعیه و کتب مذهبی",
                slug: "prayers-books",
                level: 1,
                parent: null,
                parent_id: 1,
                discount: "10%",
              },
              parent_id: 13,
              discount: "0",
            },
            parent_id: 13,
            children: [],
          },
          {
            id: 132,
            title: "قرآن - زیرگروه 2",
            slug: "prayers-books-sub3-child2",
            discount: "0",
            level: 3,
            parent: {
              id: 13,
              title: "قرآن",
              slug: "prayers-books-sub3",
              level: 2,
              parent: {
                id: 1,
                title: "ادعیه و کتب مذهبی",
                slug: "prayers-books",
                level: 1,
                parent: null,
                parent_id: 1,
                discount: "10%",
              },
              parent_id: 13,
              discount: "0",
            },
            parent_id: 13,
            children: [],
          },
        ],
        parent: {
          id: 1,
          title: "ادعیه و کتب مذهبی",
          slug: "prayers-books",
          level: 1,
          parent: null,
          parent_id: 1,
          discount: "10%",
        },
        parent_id: 1,
      },
    ],
    parent: null,
    parent_id: 0,
  },
  {
    id: 2,
    title: "عطر و لوازم شخصی",
    slug: "perfume-accessories",
    discount: "5%",
    level: 1,
    media: {
      id: 1002,
      url: "/mock/image_45.jpg",
      type: "image",
      alt_text: "تصویر عطر و لوازم شخصی",
      product_id: null,
      category_id: null,
      user_id: null,
      created_at: "2025-09-06T10:37:27.736Z",
      media: null,
    },
    children: [
      {
        id: 21,
        title: "عطر",
        slug: "perfume-accessories-sub1",
        discount: "0",
        level: 2,
        children: [
          {
            id: 211,
            title: "عطر - زیرگروه 1",
            slug: "perfume-accessories-sub1-child1",
            discount: "0",
            level: 3,
            parent: {
              id: 21,
              title: "عطر",
              slug: "perfume-accessories-sub1",
              level: 2,
              parent: {
                id: 2,
                title: "عطر و لوازم شخصی",
                slug: "perfume-accessories",
                level: 1,
                parent: null,
                parent_id: 2,
                discount: "5%",
              },
              parent_id: 21,
              discount: "0",
            },
            parent_id: 21,
            children: [],
          },
          {
            id: 212,
            title: "عطر - زیرگروه 2",
            slug: "perfume-accessories-sub1-child2",
            discount: "0",
            level: 3,
            parent: {
              id: 21,
              title: "عطر",
              slug: "perfume-accessories-sub1",
              level: 2,
              parent: {
                id: 2,
                title: "عطر و لوازم شخصی",
                slug: "perfume-accessories",
                level: 1,
                parent: null,
                parent_id: 2,
                discount: "5%",
              },
              parent_id: 21,
              discount: "0",
            },
            parent_id: 21,
            children: [],
          },
        ],
        parent: {
          id: 2,
          title: "عطر و لوازم شخصی",
          slug: "perfume-accessories",
          level: 1,
          parent: null,
          parent_id: 2,
          discount: "5%",
        },
        parent_id: 2,
      },
      {
        id: 22,
        title: "ماگ",
        slug: "perfume-accessories-sub2",
        discount: "0",
        level: 2,
        children: [
          {
            id: 221,
            title: "ماگ - زیرگروه 1",
            slug: "perfume-accessories-sub2-child1",
            discount: "0",
            level: 3,
            parent: {
              id: 22,
              title: "ماگ",
              slug: "perfume-accessories-sub2",
              level: 2,
              parent: {
                id: 2,
                title: "عطر و لوازم شخصی",
                slug: "perfume-accessories",
                level: 1,
                parent: null,
                parent_id: 2,
                discount: "5%",
              },
              parent_id: 22,
              discount: "0",
            },
            parent_id: 22,
            children: [],
          },
          {
            id: 222,
            title: "ماگ - زیرگروه 2",
            slug: "perfume-accessories-sub2-child2",
            discount: "0",
            level: 3,
            parent: {
              id: 22,
              title: "ماگ",
              slug: "perfume-accessories-sub2",
              level: 2,
              parent: {
                id: 2,
                title: "عطر و لوازم شخصی",
                slug: "perfume-accessories",
                level: 1,
                parent: null,
                parent_id: 2,
                discount: "5%",
              },
              parent_id: 22,
              discount: "0",
            },
            parent_id: 22,
            children: [],
          },
        ],
        parent: {
          id: 2,
          title: "عطر و لوازم شخصی",
          slug: "perfume-accessories",
          level: 1,
          parent: null,
          parent_id: 2,
          discount: "5%",
        },
        parent_id: 2,
      },
      {
        id: 23,
        title: "کیف",
        slug: "perfume-accessories-sub3",
        discount: "0",
        level: 2,
        children: [
          {
            id: 231,
            title: "کیف - زیرگروه 1",
            slug: "perfume-accessories-sub3-child1",
            discount: "0",
            level: 3,
            parent: {
              id: 23,
              title: "کیف",
              slug: "perfume-accessories-sub3",
              level: 2,
              parent: {
                id: 2,
                title: "عطر و لوازم شخصی",
                slug: "perfume-accessories",
                level: 1,
                parent: null,
                parent_id: 2,
                discount: "5%",
              },
              parent_id: 23,
              discount: "0",
            },
            parent_id: 23,
            children: [],
          },
          {
            id: 232,
            title: "کیف - زیرگروه 2",
            slug: "perfume-accessories-sub3-child2",
            discount: "0",
            level: 3,
            parent: {
              id: 23,
              title: "کیف",
              slug: "perfume-accessories-sub3",
              level: 2,
              parent: {
                id: 2,
                title: "عطر و لوازم شخصی",
                slug: "perfume-accessories",
                level: 1,
                parent: null,
                parent_id: 2,
                discount: "5%",
              },
              parent_id: 23,
              discount: "0",
            },
            parent_id: 23,
            children: [],
          },
        ],
        parent: {
          id: 2,
          title: "عطر و لوازم شخصی",
          slug: "perfume-accessories",
          level: 1,
          parent: null,
          parent_id: 2,
          discount: "5%",
        },
        parent_id: 2,
      },
    ],
    parent: null,
    parent_id: 0,
  },
  {
    id: 3,
    title: "مهر و تسبیح",
    slug: "mohr-tasbih",
    discount: "15%",
    level: 1,
    media: {
      id: 1002,
      url: "/mock/image_26.jpg",
      type: "image",
      alt_text: "تصویر تسبیح",
      product_id: null,
      category_id: null,
      user_id: null,
      created_at: "2025-09-06T10:37:27.736Z",
      media: null,
    },
    children: [
      {
        id: 31,
        title: "مهر",
        slug: "mohr-tasbih-sub1",
        discount: "0",
        level: 2,
        children: [
          {
            id: 311,
            title: "مهر - زیرگروه 1",
            slug: "mohr-tasbih-sub1-child1",
            discount: "0",
            level: 3,
            parent: {
              id: 31,
              title: "مهر",
              slug: "mohr-tasbih-sub1",
              level: 2,
              parent: {
                id: 3,
                title: "مهر و تسبیح",
                slug: "mohr-tasbih",
                level: 1,
                parent: null,
                parent_id: 3,
                discount: "15%",
              },
              parent_id: 31,
              discount: "0",
            },
            parent_id: 31,
            children: [],
          },
          {
            id: 312,
            title: "مهر - زیرگروه 2",
            slug: "mohr-tasbih-sub1-child2",
            discount: "0",
            level: 3,
            parent: {
              id: 31,
              title: "مهر",
              slug: "mohr-tasbih-sub1",
              level: 2,
              parent: {
                id: 3,
                title: "مهر و تسبیح",
                slug: "mohr-tasbih",
                level: 1,
                parent: null,
                parent_id: 3,
                discount: "15%",
              },
              parent_id: 31,
              discount: "0",
            },
            parent_id: 31,
            children: [],
          },
        ],
        parent: {
          id: 3,
          title: "مهر و تسبیح",
          slug: "mohr-tasbih",
          level: 1,
          parent: null,
          parent_id: 3,
          discount: "15%",
        },
        parent_id: 3,
      },
      {
        id: 32,
        title: "تسبیح چوبی",
        slug: "mohr-tasbih-sub2",
        discount: "0",
        level: 2,
        children: [
          {
            id: 321,
            title: "تسبیح چوبی - زیرگروه 1",
            slug: "mohr-tasbih-sub2-child1",
            discount: "0",
            level: 3,
            parent: {
              id: 32,
              title: "تسبیح چوبی",
              slug: "mohr-tasbih-sub2",
              level: 2,
              parent: {
                id: 3,
                title: "مهر و تسبیح",
                slug: "mohr-tasbih",
                level: 1,
                parent: null,
                parent_id: 3,
                discount: "15%",
              },
              parent_id: 32,
              discount: "0",
            },
            parent_id: 32,
            children: [],
          },
          {
            id: 322,
            title: "تسبیح چوبی - زیرگروه 2",
            slug: "mohr-tasbih-sub2-child2",
            discount: "0",
            level: 3,
            parent: {
              id: 32,
              title: "تسبیح چوبی",
              slug: "mohr-tasbih-sub2",
              level: 2,
              parent: {
                id: 3,
                title: "مهر و تسبیح",
                slug: "mohr-tasbih",
                level: 1,
                parent: null,
                parent_id: 3,
                discount: "15%",
              },
              parent_id: 32,
              discount: "0",
            },
            parent_id: 32,
            children: [],
          },
        ],
        parent: {
          id: 3,
          title: "مهر و تسبیح",
          slug: "mohr-tasbih",
          level: 1,
          parent: null,
          parent_id: 3,
          discount: "15%",
        },
        parent_id: 3,
      },
      {
        id: 33,
        title: "تسبیح سنگی",
        slug: "mohr-tasbih-sub3",
        discount: "0",
        level: 2,
        children: [
          {
            id: 331,
            title: "تسبیح سنگی - زیرگروه 1",
            slug: "mohr-tasbih-sub3-child1",
            discount: "0",
            level: 3,
            parent: {
              id: 33,
              title: "تسبیح سنگی",
              slug: "mohr-tasbih-sub3",
              level: 2,
              parent: {
                id: 3,
                title: "مهر و تسبیح",
                slug: "mohr-tasbih",
                level: 1,
                parent: null,
                parent_id: 3,
                discount: "15%",
              },
              parent_id: 33,
              discount: "0",
            },
            parent_id: 33,
            children: [],
          },
          {
            id: 332,
            title: "تسبیح سنگی - زیرگروه 2",
            slug: "mohr-tasbih-sub3-child2",
            discount: "0",
            level: 3,
            parent: {
              id: 33,
              title: "تسبیح سنگی",
              slug: "mohr-tasbih-sub3",
              level: 2,
              parent: {
                id: 3,
                title: "مهر و تسبیح",
                slug: "mohr-tasbih",
                level: 1,
                parent: null,
                parent_id: 3,
                discount: "15%",
              },
              parent_id: 33,
              discount: "0",
            },
            parent_id: 33,
            children: [],
          },
        ],
        parent: {
          id: 3,
          title: "مهر و تسبیح",
          slug: "mohr-tasbih",
          level: 1,
          parent: null,
          parent_id: 3,
          discount: "15%",
        },
        parent_id: 3,
      },
    ],
    parent: null,
    parent_id: 0,
  },
  {
    id: 4,
    title: "تندیس و دکوری",
    slug: "decor-religious",
    discount: "20%",
    level: 1,
    media: {
      id: 1005,
      url: "/mock/image_36.jpg",
      type: "image",
      alt_text: "تصویر ",
      product_id: null,
      category_id: null,
      user_id: null,
      created_at: "2025-09-06T10:37:27.736Z",
      media: null,
    },
    children: [
      {
        id: 41,
        title: "تندیس",
        slug: "decor-religious-sub1",
        discount: "0",
        level: 2,
        children: [
          {
            id: 411,
            title: "تندیس - زیرگروه 1",
            slug: "decor-religious-sub1-child1",
            discount: "0",
            level: 3,
            parent: {
              id: 41,
              title: "تندیس",
              slug: "decor-religious-sub1",
              level: 2,
              parent: {
                id: 4,
                title: "تندیس و دکوری",
                slug: "decor-religious",
                level: 1,
                parent: null,
                parent_id: 4,
                discount: "20%",
              },
              parent_id: 41,
              discount: "0",
            },
            parent_id: 41,
            children: [],
          },
          {
            id: 412,
            title: "تندیس - زیرگروه 2",
            slug: "decor-religious-sub1-child2",
            discount: "0",
            level: 3,
            parent: {
              id: 41,
              title: "تندیس",
              slug: "decor-religious-sub1",
              level: 2,
              parent: {
                id: 4,
                title: "تندیس و دکوری",
                slug: "decor-religious",
                level: 1,
                parent: null,
                parent_id: 4,
                discount: "20%",
              },
              parent_id: 41,
              discount: "0",
            },
            parent_id: 41,
            children: [],
          },
        ],
        parent: {
          id: 4,
          title: "تندیس و دکوری",
          slug: "decor-religious",
          level: 1,
          parent: null,
          parent_id: 4,
          discount: "20%",
        },
        parent_id: 4,
      },
      {
        id: 42,
        title: "تابلو",
        slug: "decor-religious-sub2",
        discount: "0",
        level: 2,
        children: [
          {
            id: 421,
            title: "تابلو - زیرگروه 1",
            slug: "decor-religious-sub2-child1",
            discount: "0",
            level: 3,
            parent: {
              id: 42,
              title: "تابلو",
              slug: "decor-religious-sub2",
              level: 2,
              parent: {
                id: 4,
                title: "تندیس و دکوری",
                slug: "decor-religious",
                level: 1,
                parent: null,
                parent_id: 4,
                discount: "20%",
              },
              parent_id: 42,
              discount: "0",
            },
            parent_id: 42,
            children: [],
          },
          {
            id: 422,
            title: "تابلو - زیرگروه 2",
            slug: "decor-religious-sub2-child2",
            discount: "0",
            level: 3,
            parent: {
              id: 42,
              title: "تابلو",
              slug: "decor-religious-sub2",
              level: 2,
              parent: {
                id: 4,
                title: "تندیس و دکوری",
                slug: "decor-religious",
                level: 1,
                parent: null,
                parent_id: 4,
                discount: "20%",
              },
              parent_id: 42,
              discount: "0",
            },
            parent_id: 42,
            children: [],
          },
        ],
        parent: {
          id: 4,
          title: "تندیس و دکوری",
          slug: "decor-religious",
          level: 1,
          parent: null,
          parent_id: 4,
          discount: "20%",
        },
        parent_id: 4,
      },
      {
        id: 43,
        title: "قاب",
        slug: "decor-religious-sub3",
        discount: "0",
        level: 2,
        children: [
          {
            id: 431,
            title: "قاب - زیرگروه 1",
            slug: "decor-religious-sub3-child1",
            discount: "0",
            level: 3,
            parent: {
              id: 43,
              title: "قاب",
              slug: "decor-religious-sub3",
              level: 2,
              parent: {
                id: 4,
                title: "تندیس و دکوری",
                slug: "decor-religious",
                level: 1,
                parent: null,
                parent_id: 4,
                discount: "20%",
              },
              parent_id: 43,
              discount: "0",
            },
            parent_id: 43,
            children: [],
          },
          {
            id: 432,
            title: "قاب - زیرگروه 2",
            slug: "decor-religious-sub3-child2",
            discount: "0",
            level: 3,
            parent: {
              id: 43,
              title: "قاب",
              slug: "decor-religious-sub3",
              level: 2,
              parent: {
                id: 4,
                title: "تندیس و دکوری",
                slug: "decor-religious",
                level: 1,
                parent: null,
                parent_id: 4,
                discount: "20%",
              },
              parent_id: 43,
              discount: "0",
            },
            parent_id: 43,
            children: [],
          },
        ],
        parent: {
          id: 4,
          title: "تندیس و دکوری",
          slug: "decor-religious",
          level: 1,
          parent: null,
          parent_id: 4,
          discount: "20%",
        },
        parent_id: 4,
      },
    ],
    parent: null,
    parent_id: 0,
  },
  {
    id: 5,
    title: "محصولات دیجیتال",
    slug: "digital-products",
    discount: "0%",
    level: 1,
    media: {
      id: 1008,
      url: "/mock/image_10.jpg",
      type: "image",
      alt_text: "تصویر ",
      product_id: null,
      category_id: null,
      user_id: null,
      created_at: "2025-09-06T10:37:27.736Z",
      media: null,
    },
    children: [
      {
        id: 51,
        title: "اسپیکر",
        slug: "digital-products-sub1",
        discount: "0",
        level: 2,
        children: [
          {
            id: 511,
            title: "اسپیکر - زیرگروه 1",
            slug: "digital-products-sub1-child1",
            discount: "0",
            level: 3,
            parent: {
              id: 51,
              title: "اسپیکر",
              slug: "digital-products-sub1",
              level: 2,
              parent: {
                id: 5,
                title: "محصولات دیجیتال",
                slug: "digital-products",
                level: 1,
                parent: null,
                parent_id: 5,
                discount: "0%",
              },
              parent_id: 51,
              discount: "0",
            },
            parent_id: 51,
            children: [],
          },
          {
            id: 512,
            title: "اسپیکر - زیرگروه 2",
            slug: "digital-products-sub1-child2",
            discount: "0",
            level: 3,
            parent: {
              id: 51,
              title: "اسپیکر",
              slug: "digital-products-sub1",
              level: 2,
              parent: {
                id: 5,
                title: "محصولات دیجیتال",
                slug: "digital-products",
                level: 1,
                parent: null,
                parent_id: 5,
                discount: "0%",
              },
              parent_id: 51,
              discount: "0",
            },
            parent_id: 51,
            children: [],
          },
        ],
        parent: {
          id: 5,
          title: "محصولات دیجیتال",
          slug: "digital-products",
          level: 1,
          parent: null,
          parent_id: 5,
          discount: "0%",
        },
        parent_id: 5,
      },
      {
        id: 52,
        title: "پاوربانک",
        slug: "digital-products-sub2",
        discount: "0",
        level: 2,
        children: [
          {
            id: 521,
            title: "پاوربانک - زیرگروه 1",
            slug: "digital-products-sub2-child1",
            discount: "0",
            level: 3,
            parent: {
              id: 52,
              title: "پاوربانک",
              slug: "digital-products-sub2",
              level: 2,
              parent: {
                id: 5,
                title: "محصولات دیجیتال",
                slug: "digital-products",
                level: 1,
                parent: null,
                parent_id: 5,
                discount: "0%",
              },
              parent_id: 52,
              discount: "0",
            },
            parent_id: 52,
            children: [],
          },
          {
            id: 522,
            title: "پاوربانک - زیرگروه 2",
            slug: "digital-products-sub2-child2",
            discount: "0",
            level: 3,
            parent: {
              id: 52,
              title: "پاوربانک",
              slug: "digital-products-sub2",
              level: 2,
              parent: {
                id: 5,
                title: "محصولات دیجیتال",
                slug: "digital-products",
                level: 1,
                parent: null,
                parent_id: 5,
                discount: "0%",
              },
              parent_id: 52,
              discount: "0",
            },
            parent_id: 52,
            children: [],
          },
        ],
        parent: {
          id: 5,
          title: "محصولات دیجیتال",
          slug: "digital-products",
          level: 1,
          parent: null,
          parent_id: 5,
          discount: "0%",
        },
        parent_id: 5,
      },
      {
        id: 53,
        title: "فلش",
        slug: "digital-products-sub3",
        discount: "0",
        level: 2,
        children: [
          {
            id: 531,
            title: "فلش - زیرگروه 1",
            slug: "digital-products-sub3-child1",
            discount: "0",
            level: 3,
            parent: {
              id: 53,
              title: "فلش",
              slug: "digital-products-sub3",
              level: 2,
              parent: {
                id: 5,
                title: "محصولات دیجیتال",
                slug: "digital-products",
                level: 1,
                parent: null,
                parent_id: 5,
                discount: "0%",
              },
              parent_id: 53,
              discount: "0",
            },
            parent_id: 53,
            children: [],
          },
          {
            id: 532,
            title: "فلش - زیرگروه 2",
            slug: "digital-products-sub3-child2",
            discount: "0",
            level: 3,
            parent: {
              id: 53,
              title: "فلش",
              slug: "digital-products-sub3",
              level: 2,
              parent: {
                id: 5,
                title: "محصولات دیجیتال",
                slug: "digital-products",
                level: 1,
                parent: null,
                parent_id: 5,
                discount: "0%",
              },
              parent_id: 53,
              discount: "0",
            },
            parent_id: 53,
            children: [],
          },
        ],
        parent: {
          id: 5,
          title: "محصولات دیجیتال",
          slug: "digital-products",
          level: 1,
          parent: null,
          parent_id: 5,
          discount: "0%",
        },
        parent_id: 5,
      },
    ],
    parent: null,
    parent_id: 0,
  },
  {
    id: 6,
    title: "پوشاک مذهبی",
    slug: "clothing",
    discount: "25%",
    level: 1,
    media: {
      id: 1004,
      url: "/mock/image_31.jpg",
      type: "image",
      alt_text: "تصویر ",
      product_id: null,
      category_id: null,
      user_id: null,
      created_at: "2025-09-06T10:37:27.736Z",
      media: null,
    },
    children: [
      {
        id: 61,
        title: "چفیه",
        slug: "clothing-sub1",
        discount: "0",
        level: 2,
        children: [
          {
            id: 611,
            title: "چفیه - زیرگروه 1",
            slug: "clothing-sub1-child1",
            discount: "0",
            level: 3,
            parent: {
              id: 61,
              title: "چفیه",
              slug: "clothing-sub1",
              level: 2,
              parent: {
                id: 6,
                title: "پوشاک مذهبی",
                slug: "clothing",
                level: 1,
                parent: null,
                parent_id: 6,
                discount: "25%",
              },
              parent_id: 61,
              discount: "0",
            },
            parent_id: 61,
            children: [],
          },
          {
            id: 612,
            title: "چفیه - زیرگروه 2",
            slug: "clothing-sub1-child2",
            discount: "0",
            level: 3,
            parent: {
              id: 61,
              title: "چفیه",
              slug: "clothing-sub1",
              level: 2,
              parent: {
                id: 6,
                title: "پوشاک مذهبی",
                slug: "clothing",
                level: 1,
                parent: null,
                parent_id: 6,
                discount: "25%",
              },
              parent_id: 61,
              discount: "0",
            },
            parent_id: 61,
            children: [],
          },
        ],
        parent: {
          id: 6,
          title: "پوشاک مذهبی",
          slug: "clothing",
          level: 1,
          parent: null,
          parent_id: 6,
          discount: "25%",
        },
        parent_id: 6,
      },
      {
        id: 62,
        title: "شال عزا",
        slug: "clothing-sub2",
        discount: "0",
        level: 2,
        children: [
          {
            id: 621,
            title: "شال عزا - زیرگروه 1",
            slug: "clothing-sub2-child1",
            discount: "0",
            level: 3,
            parent: {
              id: 62,
              title: "شال عزا",
              slug: "clothing-sub2",
              level: 2,
              parent: {
                id: 6,
                title: "پوشاک مذهبی",
                slug: "clothing",
                level: 1,
                parent: null,
                parent_id: 6,
                discount: "25%",
              },
              parent_id: 62,
              discount: "0",
            },
            parent_id: 62,
            children: [],
          },
          {
            id: 622,
            title: "شال عزا - زیرگروه 2",
            slug: "clothing-sub2-child2",
            discount: "0",
            level: 3,
            parent: {
              id: 62,
              title: "شال عزا",
              slug: "clothing-sub2",
              level: 2,
              parent: {
                id: 6,
                title: "پوشاک مذهبی",
                slug: "clothing",
                level: 1,
                parent: null,
                parent_id: 6,
                discount: "25%",
              },
              parent_id: 62,
              discount: "0",
            },
            parent_id: 62,
            children: [],
          },
        ],
        parent: {
          id: 6,
          title: "پوشاک مذهبی",
          slug: "clothing",
          level: 1,
          parent: null,
          parent_id: 6,
          discount: "25%",
        },
        parent_id: 6,
      },
      {
        id: 63,
        title: "لباس",
        slug: "clothing-sub3",
        discount: "0",
        level: 2,
        children: [
          {
            id: 631,
            title: "لباس - زیرگروه 1",
            slug: "clothing-sub3-child1",
            discount: "0",
            level: 3,
            parent: {
              id: 63,
              title: "لباس",
              slug: "clothing-sub3",
              level: 2,
              parent: {
                id: 6,
                title: "پوشاک مذهبی",
                slug: "clothing",
                level: 1,
                parent: null,
                parent_id: 6,
                discount: "25%",
              },
              parent_id: 63,
              discount: "0",
            },
            parent_id: 63,
            children: [],
          },
          {
            id: 632,
            title: "لباس - زیرگروه 2",
            slug: "clothing-sub3-child2",
            discount: "0",
            level: 3,
            parent: {
              id: 63,
              title: "لباس",
              slug: "clothing-sub3",
              level: 2,
              parent: {
                id: 6,
                title: "پوشاک مذهبی",
                slug: "clothing",
                level: 1,
                parent: null,
                parent_id: 6,
                discount: "25%",
              },
              parent_id: 63,
              discount: "0",
            },
            parent_id: 63,
            children: [],
          },
        ],
        parent: {
          id: 6,
          title: "پوشاک مذهبی",
          slug: "clothing",
          level: 1,
          parent: null,
          parent_id: 6,
          discount: "25%",
        },
        parent_id: 6,
      },
    ],
    parent: null,
    parent_id: 0,
  },
  {
    id: 7,
    title: "روشنایی مذهبی",
    slug: "lighting",
    discount: "10%",
    level: 1,
    media: {
      id: 1002,
      url: "/mock/image_46.jpg",
      type: "image",
      alt_text: "تصویر ",
      product_id: null,
      category_id: null,
      user_id: null,
      created_at: "2025-09-06T10:37:27.736Z",
      media: null,
    },
    children: [
      {
        id: 71,
        title: "چراغ خواب",
        slug: "lighting-sub1",
        discount: "0",
        level: 2,
        children: [
          {
            id: 711,
            title: "چراغ خواب - زیرگروه 1",
            slug: "lighting-sub1-child1",
            discount: "0",
            level: 3,
            parent: {
              id: 71,
              title: "چراغ خواب",
              slug: "lighting-sub1",
              level: 2,
              parent: {
                id: 7,
                title: "روشنایی مذهبی",
                slug: "lighting",
                level: 1,
                parent: null,
                parent_id: 7,
                discount: "10%",
              },
              parent_id: 71,
              discount: "0",
            },
            parent_id: 71,
            children: [],
          },
          {
            id: 712,
            title: "چراغ خواب - زیرگروه 2",
            slug: "lighting-sub1-child2",
            discount: "0",
            level: 3,
            parent: {
              id: 71,
              title: "چراغ خواب",
              slug: "lighting-sub1",
              level: 2,
              parent: {
                id: 7,
                title: "روشنایی مذهبی",
                slug: "lighting",
                level: 1,
                parent: null,
                parent_id: 7,
                discount: "10%",
              },
              parent_id: 71,
              discount: "0",
            },
            parent_id: 71,
            children: [],
          },
        ],
        parent: {
          id: 7,
          title: "روشنایی مذهبی",
          slug: "lighting",
          level: 1,
          parent: null,
          parent_id: 7,
          discount: "10%",
        },
        parent_id: 7,
      },
      {
        id: 72,
        title: "ریسه نوری",
        slug: "lighting-sub2",
        discount: "0",
        level: 2,
        children: [
          {
            id: 721,
            title: "ریسه نوری - زیرگروه 1",
            slug: "lighting-sub2-child1",
            discount: "0",
            level: 3,
            parent: {
              id: 72,
              title: "ریسه نوری",
              slug: "lighting-sub2",
              level: 2,
              parent: {
                id: 7,
                title: "روشنایی مذهبی",
                slug: "lighting",
                level: 1,
                parent: null,
                parent_id: 7,
                discount: "10%",
              },
              parent_id: 72,
              discount: "0",
            },
            parent_id: 72,
            children: [],
          },
          {
            id: 722,
            title: "ریسه نوری - زیرگروه 2",
            slug: "lighting-sub2-child2",
            discount: "0",
            level: 3,
            parent: {
              id: 72,
              title: "ریسه نوری",
              slug: "lighting-sub2",
              level: 2,
              parent: {
                id: 7,
                title: "روشنایی مذهبی",
                slug: "lighting",
                level: 1,
                parent: null,
                parent_id: 7,
                discount: "10%",
              },
              parent_id: 72,
              discount: "0",
            },
            parent_id: 72,
            children: [],
          },
        ],
        parent: {
          id: 7,
          title: "روشنایی مذهبی",
          slug: "lighting",
          level: 1,
          parent: null,
          parent_id: 7,
          discount: "10%",
        },
        parent_id: 7,
      },
      {
        id: 73,
        title: "لامپ مذهبی",
        slug: "lighting-sub3",
        discount: "0",
        level: 2,
        children: [
          {
            id: 731,
            title: "لامپ مذهبی - زیرگروه 1",
            slug: "lighting-sub3-child1",
            discount: "0",
            level: 3,
            parent: {
              id: 73,
              title: "لامپ مذهبی",
              slug: "lighting-sub3",
              level: 2,
              parent: {
                id: 7,
                title: "روشنایی مذهبی",
                slug: "lighting",
                level: 1,
                parent: null,
                parent_id: 7,
                discount: "10%",
              },
              parent_id: 73,
              discount: "0",
            },
            parent_id: 73,
            children: [],
          },
          {
            id: 732,
            title: "لامپ مذهبی - زیرگروه 2",
            slug: "lighting-sub3-child2",
            discount: "0",
            level: 3,
            parent: {
              id: 73,
              title: "لامپ مذهبی",
              slug: "lighting-sub3",
              level: 2,
              parent: {
                id: 7,
                title: "روشنایی مذهبی",
                slug: "lighting",
                level: 1,
                parent: null,
                parent_id: 7,
                discount: "10%",
              },
              parent_id: 73,
              discount: "0",
            },
            parent_id: 73,
            children: [],
          },
        ],
        parent: {
          id: 7,
          title: "روشنایی مذهبی",
          slug: "lighting",
          level: 1,
          parent: null,
          parent_id: 7,
          discount: "10%",
        },
        parent_id: 7,
      },
    ],
    parent: null,
    parent_id: 0,
  },
  {
    id: 8,
    title: "کودک و نوجوان",
    slug: "kids",
    discount: "0%",
    level: 1,
    media: {
      id: 1002,
      url: "/mock/image_44.jpg",
      type: "image",
      alt_text: "تصویر ",
      product_id: null,
      category_id: null,
      user_id: null,
      created_at: "2025-09-06T10:37:27.736Z",
      media: null,
    },
    children: [
      {
        id: 81,
        title: "کتاب کودک",
        slug: "kids-sub1",
        discount: "0",
        level: 2,
        children: [
          {
            id: 811,
            title: "کتاب کودک - زیرگروه 1",
            slug: "kids-sub1-child1",
            discount: "0",
            level: 3,
            parent: {
              id: 81,
              title: "کتاب کودک",
              slug: "kids-sub1",
              level: 2,
              parent: {
                id: 8,
                title: "کودک و نوجوان",
                slug: "kids",
                level: 1,
                parent: null,
                parent_id: 8,
                discount: "0%",
              },
              parent_id: 81,
              discount: "0",
            },
            parent_id: 81,
            children: [],
          },
          {
            id: 812,
            title: "کتاب کودک - زیرگروه 2",
            slug: "kids-sub1-child2",
            discount: "0",
            level: 3,
            parent: {
              id: 81,
              title: "کتاب کودک",
              slug: "kids-sub1",
              level: 2,
              parent: {
                id: 8,
                title: "کودک و نوجوان",
                slug: "kids",
                level: 1,
                parent: null,
                parent_id: 8,
                discount: "0%",
              },
              parent_id: 81,
              discount: "0",
            },
            parent_id: 81,
            children: [],
          },
        ],
        parent: {
          id: 8,
          title: "کودک و نوجوان",
          slug: "kids",
          level: 1,
          parent: null,
          parent_id: 8,
          discount: "0%",
        },
        parent_id: 8,
      },
      {
        id: 82,
        title: "لباس کودک",
        slug: "kids-sub2",
        discount: "0",
        level: 2,
        children: [
          {
            id: 821,
            title: "لباس کودک - زیرگروه 1",
            slug: "kids-sub2-child1",
            discount: "0",
            level: 3,
            parent: {
              id: 82,
              title: "لباس کودک",
              slug: "kids-sub2",
              level: 2,
              parent: {
                id: 8,
                title: "کودک و نوجوان",
                slug: "kids",
                level: 1,
                parent: null,
                parent_id: 8,
                discount: "0%",
              },
              parent_id: 82,
              discount: "0",
            },
            parent_id: 82,
            children: [],
          },
          {
            id: 822,
            title: "لباس کودک - زیرگروه 2",
            slug: "kids-sub2-child2",
            discount: "0",
            level: 3,
            parent: {
              id: 82,
              title: "لباس کودک",
              slug: "kids-sub2",
              level: 2,
              parent: {
                id: 8,
                title: "کودک و نوجوان",
                slug: "kids",
                level: 1,
                parent: null,
                parent_id: 8,
                discount: "0%",
              },
              parent_id: 82,
              discount: "0",
            },
            parent_id: 82,
            children: [],
          },
        ],
        parent: {
          id: 8,
          title: "کودک و نوجوان",
          slug: "kids",
          level: 1,
          parent: null,
          parent_id: 8,
          discount: "0%",
        },
        parent_id: 8,
      },
      {
        id: 83,
        title: "بازی",
        slug: "kids-sub3",
        discount: "0",
        level: 2,
        children: [
          {
            id: 831,
            title: "بازی - زیرگروه 1",
            slug: "kids-sub3-child1",
            discount: "0",
            level: 3,
            parent: {
              id: 83,
              title: "بازی",
              slug: "kids-sub3",
              level: 2,
              parent: {
                id: 8,
                title: "کودک و نوجوان",
                slug: "kids",
                level: 1,
                parent: null,
                parent_id: 8,
                discount: "0%",
              },
              parent_id: 83,
              discount: "0",
            },
            parent_id: 83,
            children: [],
          },
          {
            id: 832,
            title: "بازی - زیرگروه 2",
            slug: "kids-sub3-child2",
            discount: "0",
            level: 3,
            parent: {
              id: 83,
              title: "بازی",
              slug: "kids-sub3",
              level: 2,
              parent: {
                id: 8,
                title: "کودک و نوجوان",
                slug: "kids",
                level: 1,
                parent: null,
                parent_id: 8,
                discount: "0%",
              },
              parent_id: 83,
              discount: "0",
            },
            parent_id: 83,
            children: [],
          },
        ],
        parent: {
          id: 8,
          title: "کودک و نوجوان",
          slug: "kids",
          level: 1,
          parent: null,
          parent_id: 8,
          discount: "0%",
        },
        parent_id: 8,
      },
    ],
    parent: null,
    parent_id: 0,
  },
];

export const products: Product[] = [
  {
    id: 1,
    name: "قرآن‌کریم رقعی مخصوص حفظ",
    price: "208135",
    stock: 10,
    is_same_day_shipping: true,
    requires_preparation: false,
    preparation_days: 2,
    is_limited_stock: true,
    discount_amount: "50218",
    discount_percent: 30,
    is_featured: false,
    weight: "1.46",
    weight_unit: "kg",
    description: "توضیحات تستی برای قرآن‌کریم رقعی مخصوص حفظ",
    is_visible: true,
    order_limit: 3,
    category_id: 71,
    media_pinned_id: 101,
    helper_id: null,
    helper: null,
    brand_id: 8,
    created_at: "2025-09-06T10:37:27.736Z",
    updated_at: "2025-09-06T10:37:27.736Z",
    medias: [
      {
        id: 101,
        url: "/mock/image_31.jpg",
        type: "image",
        alt_text: "تصویر محصول 1",
        product_id: 1,
        category_id: null,
        user_id: null,
        created_at: "2025-09-06T10:37:27.736Z",
        media: null,
      },
      {
        id: 102,
        url: "/mock/image_23.jpg",
        type: "image",
        alt_text: "تصویر بندانگشتی محصول 1",
        product_id: 1,
        category_id: null,
        user_id: null,
        created_at: "2025-09-06T10:37:27.736Z",
        media: null,
      },
      {
        id: 103,
        url: "/mock/image_24.jpg",
        type: "image",
        alt_text: "تصویر بندانگشتی محصول 1",
        product_id: 1,
        category_id: null,
        user_id: null,
        created_at: "2025-09-06T10:37:27.736Z",
        media: null,
      },
      {
        id: 104,
        url: "/mock/image_25.jpg",
        type: "image",
        alt_text: "تصویر بندانگشتی محصول 1",
        product_id: 1,
        category_id: null,
        user_id: null,
        created_at: "2025-09-06T10:37:27.736Z",
        media: null,
      },
      {
        id: 106,
        url: "/mock/image_26.jpg",
        type: "image",
        alt_text: "تصویر بندانگشتی محصول 1",
        product_id: 1,
        category_id: null,
        user_id: null,
        created_at: "2025-09-06T10:37:27.736Z",
        media: null,
      },
      {
        id: 107,
        url: "/mock/image_29.jpg",
        type: "image",
        alt_text: "تصویر بندانگشتی محصول 1",
        product_id: 1,
        category_id: null,
        user_id: null,
        created_at: "2025-09-06T10:37:27.736Z",
        media: null,
      },
      {
        id: 108,
        url: "/mock/image_30.jpg",
        type: "image",
        alt_text: "تصویر بندانگشتی محصول 1",
        product_id: 1,
        category_id: null,
        user_id: null,
        created_at: "2025-09-06T10:37:27.736Z",
        media: null,
      },
      {
        id: 109,
        url: "https://dl.poshtybanman.ir/alfbaye-sarbazi-hazrt-hojat/2.mp4",
        type: "video",
        alt_text: "تصویر بندانگشتی محصول 1",
        product_id: 1,
        category_id: null,
        user_id: null,
        created_at: "2025-09-06T10:37:27.736Z",
        media: null,
      },
    ],
    media_pinned: {
      id: 101,
      url: "/mock/image_31.jpg",
      type: "image",
      alt_text: "تصویر محصول 1",
      product_id: 1,
      category_id: null,
      user_id: null,
      created_at: "2025-09-06T10:37:27.736Z",
      media: null,
    },
    brand: {
      id: 8,
      name: "اسپیکر‌استار",
      logo: "/images/brands/speakerstar.png",
    },
    category: {
      id: 71,
      title: "چراغ خواب",
      slug: "lighting-sub1",
      level: 2,
      parent: {
        id: 7,
        title: "روشنایی مذهبی",
        slug: "lighting",
        level: 1,
        parent: null,
        parent_id: 7,
        discount: "10%",
      },
      parent_id: 7,
    },
    attribute_nodes: [],
    specifications: [],
    variants: [],
    count: 0,
    average_rating: 3.5,
    items: [],
  },
  {
    id: 2,
    name: "سنگ نگین همراه تربت",
    price: "60900",
    stock: 11,
    is_same_day_shipping: true,
    requires_preparation: false,
    preparation_days: 1,
    is_limited_stock: true,
    discount_amount: "93631",
    discount_percent: 46,
    is_featured: false,
    weight: "1.87",
    weight_unit: "kg",
    description: "توضیحات تستی برای سنگ نگین همراه تربت",
    is_visible: true,
    order_limit: 4,
    category_id: 72,
    media_pinned_id: 201,
    helper_id: null,
    helper: null,
    brand_id: 7,
    created_at: "2025-09-06T10:37:27.736Z",
    updated_at: "2025-09-06T10:37:27.736Z",
    medias: [
      {
        id: 201,
        url: "/mock/image_2.jpg",
        type: "image",
        alt_text: "تصویر محصول 2",
        product_id: 2,
        category_id: null,
        user_id: null,
        created_at: "2025-09-06T10:37:27.736Z",
        media: null,
      },
      {
        id: 202,
        url: "/mock/image_41.jpg",
        type: "image",
        alt_text: "تصویر بندانگشتی محصول 2",
        product_id: 2,
        category_id: null,
        user_id: null,
        created_at: "2025-09-06T10:37:27.736Z",
        media: null,
      },
    ],
    media_pinned: {
      id: 201,
      url: "/mock/image_2.jpg",
      type: "image",
      alt_text: "تصویر محصول 2",
      product_id: 2,
      category_id: null,
      user_id: null,
      created_at: "2025-09-06T10:37:27.736Z",
      media: null,
    },
    brand: {
      id: 7,
      name: "ماگ‌لند",
      logo: "/images/brands/mugland.png",
    },
    category: {
      id: 72,
      title: "ریسه نوری",
      slug: "lighting-sub2",
      level: 2,
      parent: {
        id: 7,
        title: "روشنایی مذهبی",
        slug: "lighting",
        level: 1,
        parent: null,
        parent_id: 7,
        discount: "10%",
      },
      parent_id: 7,
    },
    attribute_nodes: [],
    specifications: [],
    variants: [],
    count: 0,
    average_rating: 3.5,
    items: [],
  },
  {
    id: 3,
    name: "قرآن وزیری ترمو ترجمه کلمه به کلمه",
    price: "401753",
    stock: 5,
    is_same_day_shipping: true,
    requires_preparation: false,
    preparation_days: 5,
    is_limited_stock: false,
    discount_amount: "32772",
    discount_percent: 9,
    is_featured: true,
    weight: "1.98",
    weight_unit: "kg",
    description: "توضیحات تستی برای قرآن وزیری ترمو ترجمه کلمه به کلمه",
    is_visible: true,
    order_limit: 3,
    category_id: 61,
    media_pinned_id: 301,
    helper_id: null,
    helper: null,
    brand_id: 1,
    created_at: "2025-09-06T10:37:27.736Z",
    updated_at: "2025-09-06T10:37:27.736Z",
    medias: [
      {
        id: 301,
        url: "/mock/image_3.jpg",
        type: "image",
        alt_text: "تصویر محصول 3",
        product_id: 3,
        category_id: null,
        user_id: null,
        created_at: "2025-09-06T10:37:27.736Z",
        media: null,
      },
      {
        id: 302,
        url: "/mock/image_1.jpg",
        type: "image",
        alt_text: "تصویر بندانگشتی محصول 3",
        product_id: 3,
        category_id: null,
        user_id: null,
        created_at: "2025-09-06T10:37:27.736Z",
        media: null,
      },
    ],
    media_pinned: {
      id: 301,
      url: "/mock/image_3.jpg",
      type: "image",
      alt_text: "تصویر محصول 3",
      product_id: 3,
      category_id: null,
      user_id: null,
      created_at: "2025-09-06T10:37:27.736Z",
      media: null,
    },
    brand: {
      id: 1,
      name: "مهرآسا",
      logo: "/images/brands/mehrasa.png",
    },
    category: {
      id: 61,
      title: "چفیه",
      slug: "clothing-sub1",
      level: 2,
      parent: {
        id: 6,
        title: "پوشاک مذهبی",
        slug: "clothing",
        level: 1,
        parent: null,
        parent_id: 6,
        discount: "25%",
      },
      parent_id: 6,
    },
    attribute_nodes: [],
    specifications: [],
    variants: [],
    count: 0,
    average_rating: 3.5,
    items: [],
  },
  {
    id: 4,
    name: "مصحف همراه (طلاکوب)",
    price: "124951",
    stock: 76,
    is_same_day_shipping: false,
    requires_preparation: false,
    preparation_days: null,
    is_limited_stock: false,
    discount_amount: "67504",
    discount_percent: 1,
    is_featured: false,
    weight: "0.26",
    weight_unit: "kg",
    description: "توضیحات تستی برای مصحف همراه (طلاکوب)",
    is_visible: true,
    order_limit: 2,
    category_id: 13,
    media_pinned_id: 401,
    helper_id: null,
    helper: null,
    brand_id: 4,
    created_at: "2025-09-06T10:37:27.736Z",
    updated_at: "2025-09-06T10:37:27.736Z",
    medias: [
      {
        id: 401,
        url: "/mock/image_40.jpg",
        type: "image",
        alt_text: "تصویر محصول 4",
        product_id: 4,
        category_id: null,
        user_id: null,
        created_at: "2025-09-06T10:37:27.736Z",
        media: null,
      },
      {
        id: 402,
        url: "/mock/image_29.jpg",
        type: "image",
        alt_text: "تصویر بندانگشتی محصول 4",
        product_id: 4,
        category_id: null,
        user_id: null,
        created_at: "2025-09-06T10:37:27.736Z",
        media: null,
      },
    ],
    media_pinned: {
      id: 401,
      url: "/mock/image_40.jpg",
      type: "image",
      alt_text: "تصویر محصول 4",
      product_id: 4,
      category_id: null,
      user_id: null,
      created_at: "2025-09-06T10:37:27.736Z",
      media: null,
    },
    brand: {
      id: 4,
      name: "کتاب دعا",
      logo: "/images/brands/bookdua.png",
    },
    category: {
      id: 13,
      title: "قرآن",
      slug: "prayers-books-sub3",
      level: 2,
      parent: {
        id: 1,
        title: "ادعیه و کتب مذهبی",
        slug: "prayers-books",
        level: 1,
        parent: null,
        parent_id: 1,
        discount: "10%",
      },
      parent_id: 1,
    },
    attribute_nodes: [],
    specifications: [],
    variants: [],
    count: 0,
    average_rating: 3.5,
    items: [],
  },
  {
    id: 5,
    name: "تابلو مدرن دکوراتیو مذهبی",
    price: "351625",
    stock: 17,
    is_same_day_shipping: false,
    requires_preparation: true,
    preparation_days: null,
    is_limited_stock: true,
    discount_amount: "37940",
    discount_percent: 23,
    is_featured: true,
    weight: "0.70",
    weight_unit: "kg",
    description: "توضیحات تستی برای تابلو مدرن دکوراتیو مذهبی",
    is_visible: true,
    order_limit: 5,
    category_id: 41,
    media_pinned_id: 501,
    helper_id: null,
    helper: null,
    brand_id: 6,
    created_at: "2025-09-06T10:37:27.736Z",
    updated_at: "2025-09-06T10:37:27.736Z",
    medias: [
      {
        id: 501,
        url: "/mock/image_17.jpg",
        type: "image",
        alt_text: "تصویر محصول 5",
        product_id: 5,
        category_id: null,
        user_id: null,
        created_at: "2025-09-06T10:37:27.736Z",
        media: null,
      },
      {
        id: 502,
        url: "/mock/image_15.jpg",
        type: "image",
        alt_text: "تصویر بندانگشتی محصول 5",
        product_id: 5,
        category_id: null,
        user_id: null,
        created_at: "2025-09-06T10:37:27.736Z",
        media: null,
      },
    ],
    media_pinned: {
      id: 501,
      url: "/mock/image_17.jpg",
      type: "image",
      alt_text: "تصویر محصول 5",
      product_id: 5,
      category_id: null,
      user_id: null,
      created_at: "2025-09-06T10:37:27.736Z",
      media: null,
    },
    brand: {
      id: 6,
      name: "دیجیتال‌پلاس",
      logo: "/images/brands/digitalplus.png",
    },
    category: {
      id: 41,
      title: "تندیس",
      slug: "decor-religious-sub1",
      level: 2,
      parent: {
        id: 4,
        title: "تندیس و دکوری",
        slug: "decor-religious",
        level: 1,
        parent: null,
        parent_id: 4,
        discount: "20%",
      },
      parent_id: 4,
    },
    attribute_nodes: [],
    specifications: [],
    variants: [],
    count: 0,
    average_rating: 3.5,
    items: [],
  },
  {
    id: 6,
    name: "تسبیح تایگر (چشم ببر)",
    price: "123052",
    stock: 48,
    is_same_day_shipping: false,
    requires_preparation: false,
    preparation_days: 3,
    is_limited_stock: false,
    discount_amount: "38405",
    discount_percent: 14,
    is_featured: false,
    weight: "1.96",
    weight_unit: "kg",
    description: "توضیحات تستی برای تسبیح تایگر (چشم ببر)",
    is_visible: true,
    order_limit: 3,
    category_id: 32,
    media_pinned_id: 601,
    helper_id: null,
    helper: null,
    brand_id: 8,
    created_at: "2025-09-06T10:37:27.736Z",
    updated_at: "2025-09-06T10:37:27.736Z",
    medias: [
      {
        id: 601,
        url: "/mock/image_52.jpg",
        type: "image",
        alt_text: "تصویر محصول 6",
        product_id: 6,
        category_id: null,
        user_id: null,
        created_at: "2025-09-06T10:37:27.736Z",
        media: null,
      },
      {
        id: 602,
        url: "/mock/image_45.jpg",
        type: "image",
        alt_text: "تصویر بندانگشتی محصول 6",
        product_id: 6,
        category_id: null,
        user_id: null,
        created_at: "2025-09-06T10:37:27.736Z",
        media: null,
      },
    ],
    media_pinned: {
      id: 601,
      url: "/mock/image_52.jpg",
      type: "image",
      alt_text: "تصویر محصول 6",
      product_id: 6,
      category_id: null,
      user_id: null,
      created_at: "2025-09-06T10:37:27.736Z",
      media: null,
    },
    brand: {
      id: 8,
      name: "اسپیکر‌استار",
      logo: "/images/brands/speakerstar.png",
    },
    category: {
      id: 32,
      title: "تسبیح چوبی",
      slug: "mohr-tasbih-sub2",
      level: 2,
      parent: {
        id: 3,
        title: "مهر و تسبیح",
        slug: "mohr-tasbih",
        level: 1,
        parent: null,
        parent_id: 3,
        discount: "15%",
      },
      parent_id: 3,
    },
    attribute_nodes: [],
    specifications: [],
    variants: [],
    count: 0,
    average_rating: 3.5,
    items: [],
  },
  {
    id: 7,
    name: "تسبیح عقیق شجر ترکیده سرخ",
    price: "46965",
    stock: 94,
    is_same_day_shipping: false,
    requires_preparation: true,
    preparation_days: 2,
    is_limited_stock: true,
    discount_amount: "37710",
    discount_percent: 44,
    is_featured: true,
    weight: "1.86",
    weight_unit: "kg",
    description: "توضیحات تستی برای تسبیح عقیق شجر ترکیده سرخ",
    is_visible: true,
    order_limit: 3,
    category_id: 82,
    media_pinned_id: 701,
    helper_id: null,
    helper: null,
    brand_id: 4,
    created_at: "2025-09-06T10:37:27.736Z",
    updated_at: "2025-09-06T10:37:27.736Z",
    medias: [
      {
        id: 701,
        url: "/mock/image_41.jpg",
        type: "image",
        alt_text: "تصویر محصول 7",
        product_id: 7,
        category_id: null,
        user_id: null,
        created_at: "2025-09-06T10:37:27.736Z",
        media: null,
      },
      {
        id: 702,
        url: "/mock/image_18.jpg",
        type: "image",
        alt_text: "تصویر بندانگشتی محصول 7",
        product_id: 7,
        category_id: null,
        user_id: null,
        created_at: "2025-09-06T10:37:27.736Z",
        media: null,
      },
    ],
    media_pinned: {
      id: 701,
      url: "/mock/image_41.jpg",
      type: "image",
      alt_text: "تصویر محصول 7",
      product_id: 7,
      category_id: null,
      user_id: null,
      created_at: "2025-09-06T10:37:27.736Z",
      media: null,
    },
    brand: {
      id: 4,
      name: "کتاب دعا",
      logo: "/images/brands/bookdua.png",
    },
    category: {
      id: 82,
      title: "لباس کودک",
      slug: "kids-sub2",
      level: 2,
      parent: {
        id: 8,
        title: "کودک و نوجوان",
        slug: "kids",
        level: 1,
        parent: null,
        parent_id: 8,
        discount: "0%",
      },
      parent_id: 8,
    },
    attribute_nodes: [],
    specifications: [],
    variants: [],
    count: 0,
    average_rating: 3.5,
    items: [],
  },
  {
    id: 8,
    name: "استند رومیزی علی ولی الله",
    price: "654325",
    stock: 47,
    is_same_day_shipping: false,
    requires_preparation: true,
    preparation_days: 1,
    is_limited_stock: false,
    discount_amount: "62557",
    discount_percent: 35,
    is_featured: false,
    weight: "1.74",
    weight_unit: "kg",
    description: "توضیحات تستی برای استند رومیزی علی ولی الله",
    is_visible: true,
    order_limit: 5,
    category_id: 63,
    media_pinned_id: 801,
    helper_id: null,
    helper: null,
    brand_id: 5,
    created_at: "2025-09-06T10:37:27.736Z",
    updated_at: "2025-09-06T10:37:27.736Z",
    medias: [
      {
        id: 801,
        url: "/mock/image_6.jpg",
        type: "image",
        alt_text: "تصویر محصول 8",
        product_id: 8,
        category_id: null,
        user_id: null,
        created_at: "2025-09-06T10:37:27.736Z",
        media: null,
      },
      {
        id: 802,
        url: "/mock/image_21.jpg",
        type: "image",
        alt_text: "تصویر بندانگشتی محصول 8",
        product_id: 8,
        category_id: null,
        user_id: null,
        created_at: "2025-09-06T10:37:27.736Z",
        media: null,
      },
    ],
    media_pinned: {
      id: 801,
      url: "/mock/image_6.jpg",
      type: "image",
      alt_text: "تصویر محصول 8",
      product_id: 8,
      category_id: null,
      user_id: null,
      created_at: "2025-09-06T10:37:27.736Z",
      media: null,
    },
    brand: {
      id: 5,
      name: "چراغین",
      logo: "/images/brands/cheraghin.png",
    },
    category: {
      id: 63,
      title: "لباس",
      slug: "clothing-sub3",
      level: 2,
      parent: {
        id: 6,
        title: "پوشاک مذهبی",
        slug: "clothing",
        level: 1,
        parent: null,
        parent_id: 6,
        discount: "25%",
      },
      parent_id: 6,
    },
    attribute_nodes: [],
    specifications: [],
    variants: [],
    count: 0,
    average_rating: 3.5,
    items: [],
  },
  {
    id: 9,
    name: "نیم‌ست نقره طرح پروانه",
    price: "159715",
    stock: 85,
    is_same_day_shipping: true,
    requires_preparation: false,
    preparation_days: 1,
    is_limited_stock: false,
    discount_amount: "13246",
    discount_percent: 8,
    is_featured: false,
    weight: "1.47",
    weight_unit: "kg",
    description: "توضیحات تستی برای نیم‌ست نقره طرح پروانه",
    is_visible: true,
    order_limit: 2,
    category_id: 31,
    media_pinned_id: 901,
    helper_id: null,
    helper: null,
    brand_id: 2,
    created_at: "2025-09-06T10:37:27.736Z",
    updated_at: "2025-09-06T10:37:27.736Z",
    medias: [
      {
        id: 901,
        url: "/mock/image_7.jpg",
        type: "image",
        alt_text: "تصویر محصول 9",
        product_id: 9,
        category_id: null,
        user_id: null,
        created_at: "2025-09-06T10:37:27.736Z",
        media: null,
      },
      {
        id: 902,
        url: "/mock/image_48.jpg",
        type: "image",
        alt_text: "تصویر بندانگشتی محصول 9",
        product_id: 9,
        category_id: null,
        user_id: null,
        created_at: "2025-09-06T10:37:27.736Z",
        media: null,
      },
    ],
    media_pinned: {
      id: 901,
      url: "/mock/image_7.jpg",
      type: "image",
      alt_text: "تصویر محصول 9",
      product_id: 9,
      category_id: null,
      user_id: null,
      created_at: "2025-09-06T10:37:27.736Z",
      media: null,
    },
    brand: {
      id: 2,
      name: "عطر نیک",
      logo: "/images/brands/atrnik.png",
    },
    category: {
      id: 31,
      title: "مهر",
      slug: "mohr-tasbih-sub1",
      level: 2,
      parent: {
        id: 3,
        title: "مهر و تسبیح",
        slug: "mohr-tasbih",
        level: 1,
        parent: null,
        parent_id: 3,
        discount: "15%",
      },
      parent_id: 3,
    },
    attribute_nodes: [],
    specifications: [],
    variants: [],
    count: 0,
    average_rating: 3.5,
    items: [],
  },
  {
    id: 10,
    name: "تسبیح فیروزه نیشابوری اصل",
    price: "495492",
    stock: 2,
    is_same_day_shipping: false,
    requires_preparation: true,
    preparation_days: 1,
    is_limited_stock: false,
    discount_amount: "32261",
    discount_percent: 0,
    is_featured: false,
    weight: "1.74",
    weight_unit: "kg",
    description: "توضیحات تستی برای تسبیح فیروزه نیشابوری اصل",
    is_visible: true,
    order_limit: 2,
    category_id: 32,
    media_pinned_id: 1001,
    helper_id: null,
    helper: null,
    brand_id: 8,
    created_at: "2025-09-06T10:37:27.736Z",
    updated_at: "2025-09-06T10:37:27.736Z",
    medias: [
      {
        id: 1001,
        url: "/mock/image_18.jpg",
        type: "image",
        alt_text: "تصویر محصول 10",
        product_id: 10,
        category_id: null,
        user_id: null,
        created_at: "2025-09-06T10:37:27.736Z",
        media: null,
      },
      {
        id: 1002,
        url: "/mock/image_40.jpg",
        type: "image",
        alt_text: "تصویر بندانگشتی محصول 10",
        product_id: 10,
        category_id: null,
        user_id: null,
        created_at: "2025-09-06T10:37:27.736Z",
        media: null,
      },
    ],
    media_pinned: {
      id: 1001,
      url: "/mock/image_18.jpg",
      type: "image",
      alt_text: "تصویر محصول 10",
      product_id: 10,
      category_id: null,
      user_id: null,
      created_at: "2025-09-06T10:37:27.736Z",
      media: null,
    },
    brand: {
      id: 8,
      name: "اسپیکر‌استار",
      logo: "/images/brands/speakerstar.png",
    },
    category: {
      id: 32,
      title: "تسبیح چوبی",
      slug: "mohr-tasbih-sub2",
      level: 2,
      parent: {
        id: 3,
        title: "مهر و تسبیح",
        slug: "mohr-tasbih",
        level: 1,
        parent: null,
        parent_id: 3,
        discount: "15%",
      },
      parent_id: 3,
    },
    attribute_nodes: [],
    specifications: [],
    variants: [],
    count: 0,
    average_rating: 3.5,
    items: [],
  },
  {
    id: 11,
    name: "قاب آیه‌الکرسی با خط نستعلیق",
    price: "325609",
    stock: 27,
    is_same_day_shipping: true,
    requires_preparation: false,
    preparation_days: null,
    is_limited_stock: true,
    discount_amount: "61853",
    discount_percent: 45,
    is_featured: false,
    weight: "0.23",
    weight_unit: "kg",
    description: "توضیحات تستی برای قاب آیه‌الکرسی با خط نستعلیق",
    is_visible: true,
    order_limit: 2,
    category_id: 71,
    media_pinned_id: 1101,
    helper_id: null,
    helper: null,
    brand_id: 7,
    created_at: "2025-09-06T10:37:27.736Z",
    updated_at: "2025-09-06T10:37:27.736Z",
    medias: [
      {
        id: 1101,
        url: "/mock/image_48.jpg",
        type: "image",
        alt_text: "تصویر محصول 11",
        product_id: 11,
        category_id: null,
        user_id: null,
        created_at: "2025-09-06T10:37:27.736Z",
        media: null,
      },
      {
        id: 1102,
        url: "/mock/image_37.jpg",
        type: "image",
        alt_text: "تصویر بندانگشتی محصول 11",
        product_id: 11,
        category_id: null,
        user_id: null,
        created_at: "2025-09-06T10:37:27.736Z",
        media: null,
      },
    ],
    media_pinned: {
      id: 1101,
      url: "/mock/image_48.jpg",
      type: "image",
      alt_text: "تصویر محصول 11",
      product_id: 11,
      category_id: null,
      user_id: null,
      created_at: "2025-09-06T10:37:27.736Z",
      media: null,
    },
    brand: {
      id: 7,
      name: "ماگ‌لند",
      logo: "/images/brands/mugland.png",
    },
    category: {
      id: 71,
      title: "چراغ خواب",
      slug: "lighting-sub1",
      level: 2,
      parent: {
        id: 7,
        title: "روشنایی مذهبی",
        slug: "lighting",
        level: 1,
        parent: null,
        parent_id: 7,
        discount: "10%",
      },
      parent_id: 7,
    },
    attribute_nodes: [],
    specifications: [],
    variants: [],
    count: 0,
    average_rating: 3.5,
    items: [],
  },
  {
    id: 12,
    name: "جا قرآنی چوبی منبت‌کاری شده",
    price: "335622",
    stock: 63,
    is_same_day_shipping: false,
    requires_preparation: false,
    preparation_days: null,
    is_limited_stock: false,
    discount_amount: "11415",
    discount_percent: 5,
    is_featured: true,
    weight: "1.08",
    weight_unit: "kg",
    description: "توضیحات تستی برای جا قرآنی چوبی منبت‌کاری شده",
    is_visible: true,
    order_limit: 2,
    category_id: 23,
    media_pinned_id: 1201,
    helper_id: null,
    helper: null,
    brand_id: 8,
    created_at: "2025-09-06T10:37:27.736Z",
    updated_at: "2025-09-06T10:37:27.736Z",
    medias: [
      {
        id: 1201,
        url: "/mock/image_32.jpg",
        type: "image",
        alt_text: "تصویر محصول 12",
        product_id: 12,
        category_id: null,
        user_id: null,
        created_at: "2025-09-06T10:37:27.736Z",
        media: null,
      },
      {
        id: 1202,
        url: "/mock/image_31.jpg",
        type: "image",
        alt_text: "تصویر بندانگشتی محصول 12",
        product_id: 12,
        category_id: null,
        user_id: null,
        created_at: "2025-09-06T10:37:27.736Z",
        media: null,
      },
    ],
    media_pinned: {
      id: 1201,
      url: "/mock/image_32.jpg",
      type: "image",
      alt_text: "تصویر محصول 12",
      product_id: 12,
      category_id: null,
      user_id: null,
      created_at: "2025-09-06T10:37:27.736Z",
      media: null,
    },
    brand: {
      id: 8,
      name: "اسپیکر‌استار",
      logo: "/images/brands/speakerstar.png",
    },
    category: {
      id: 23,
      title: "کیف",
      slug: "perfume-accessories-sub3",
      level: 2,
      parent: {
        id: 2,
        title: "عطر و لوازم شخصی",
        slug: "perfume-accessories",
        level: 1,
        parent: null,
        parent_id: 2,
        discount: "5%",
      },
      parent_id: 2,
    },
    attribute_nodes: [],
    specifications: [],
    variants: [],
    count: 0,
    average_rating: 3.5,
    items: [],
  },
  {
    id: 13,
    name: "مهر تربت کربلا با قاب مخملی",
    price: "531699",
    stock: 73,
    is_same_day_shipping: true,
    requires_preparation: false,
    preparation_days: 5,
    is_limited_stock: false,
    discount_amount: "37232",
    discount_percent: 49,
    is_featured: false,
    weight: "0.55",
    weight_unit: "kg",
    description: "توضیحات تستی برای مهر تربت کربلا با قاب مخملی",
    is_visible: true,
    order_limit: 3,
    category_id: 31,
    media_pinned_id: 1301,
    helper_id: null,
    helper: null,
    brand_id: 3,
    created_at: "2025-09-06T10:37:27.736Z",
    updated_at: "2025-09-06T10:37:27.736Z",
    medias: [
      {
        id: 1301,
        url: "/mock/image_11.jpg",
        type: "image",
        alt_text: "تصویر محصول 13",
        product_id: 13,
        category_id: null,
        user_id: null,
        created_at: "2025-09-06T10:37:27.736Z",
        media: null,
      },
      {
        id: 1302,
        url: "/mock/image_45.jpg",
        type: "image",
        alt_text: "تصویر بندانگشتی محصول 13",
        product_id: 13,
        category_id: null,
        user_id: null,
        created_at: "2025-09-06T10:37:27.736Z",
        media: null,
      },
    ],
    media_pinned: {
      id: 1301,
      url: "/mock/image_11.jpg",
      type: "image",
      alt_text: "تصویر محصول 13",
      product_id: 13,
      category_id: null,
      user_id: null,
      created_at: "2025-09-06T10:37:27.736Z",
      media: null,
    },
    brand: {
      id: 3,
      name: "تسبیح‌کو",
      logo: "/images/brands/tasbihco.png",
    },
    category: {
      id: 31,
      title: "مهر",
      slug: "mohr-tasbih-sub1",
      level: 2,
      parent: {
        id: 3,
        title: "مهر و تسبیح",
        slug: "mohr-tasbih",
        level: 1,
        parent: null,
        parent_id: 3,
        discount: "15%",
      },
      parent_id: 3,
    },
    attribute_nodes: [],
    specifications: [],
    variants: [],
    count: 0,
    average_rating: 3.5,
    items: [],
  },
  {
    id: 14,
    name: "آویز ماشین با ذکر یا حسین",
    price: "653910",
    stock: 0,
    is_same_day_shipping: false,
    requires_preparation: true,
    preparation_days: null,
    is_limited_stock: true,
    discount_amount: "74492",
    discount_percent: 30,
    is_featured: false,
    weight: "1.30",
    weight_unit: "kg",
    description: "توضیحات تستی برای آویز ماشین با ذکر یا حسین",
    is_visible: true,
    order_limit: 5,
    category_id: 33,
    media_pinned_id: 1401,
    helper_id: null,
    helper: null,
    brand_id: 1,
    created_at: "2025-09-06T10:37:27.736Z",
    updated_at: "2025-09-06T10:37:27.736Z",
    medias: [
      {
        id: 1401,
        url: "/mock/image_18.jpg",
        type: "image",
        alt_text: "تصویر محصول 14",
        product_id: 14,
        category_id: null,
        user_id: null,
        created_at: "2025-09-06T10:37:27.736Z",
        media: null,
      },
      {
        id: 1402,
        url: "/mock/image_19.jpg",
        type: "image",
        alt_text: "تصویر بندانگشتی محصول 14",
        product_id: 14,
        category_id: null,
        user_id: null,
        created_at: "2025-09-06T10:37:27.736Z",
        media: null,
      },
    ],
    media_pinned: {
      id: 1401,
      url: "/mock/image_18.jpg",
      type: "image",
      alt_text: "تصویر محصول 14",
      product_id: 14,
      category_id: null,
      user_id: null,
      created_at: "2025-09-06T10:37:27.736Z",
      media: null,
    },
    brand: {
      id: 1,
      name: "مهرآسا",
      logo: "/images/brands/mehrasa.png",
    },
    category: {
      id: 33,
      title: "تسبیح سنگی",
      slug: "mohr-tasbih-sub3",
      level: 2,
      parent: {
        id: 3,
        title: "مهر و تسبیح",
        slug: "mohr-tasbih",
        level: 1,
        parent: null,
        parent_id: 3,
        discount: "15%",
      },
      parent_id: 3,
    },
    attribute_nodes: [],
    specifications: [],
    variants: [],
    count: 0,
    average_rating: 3.5,
    items: [],
  },
  {
    id: 15,
    name: "شمع تزئینی با طرح اسماءالله",
    price: "400405",
    stock: 54,
    is_same_day_shipping: false,
    requires_preparation: false,
    preparation_days: 4,
    is_limited_stock: false,
    discount_amount: "73273",
    discount_percent: 8,
    is_featured: true,
    weight: "0.46",
    weight_unit: "kg",
    description: "توضیحات تستی برای شمع تزئینی با طرح اسماءالله",
    is_visible: true,
    order_limit: 4,
    category_id: 33,
    media_pinned_id: 1501,
    helper_id: null,
    helper: null,
    brand_id: 7,
    created_at: "2025-09-06T10:37:27.736Z",
    updated_at: "2025-09-06T10:37:27.736Z",
    medias: [
      {
        id: 1501,
        url: "/mock/image_20.jpg",
        type: "image",
        alt_text: "تصویر محصول 15",
        product_id: 15,
        category_id: null,
        user_id: null,
        created_at: "2025-09-06T10:37:27.736Z",
        media: null,
      },
      {
        id: 1502,
        url: "/mock/image_32.jpg",
        type: "image",
        alt_text: "تصویر بندانگشتی محصول 15",
        product_id: 15,
        category_id: null,
        user_id: null,
        created_at: "2025-09-06T10:37:27.736Z",
        media: null,
      },
    ],
    media_pinned: {
      id: 1501,
      url: "/mock/image_20.jpg",
      type: "image",
      alt_text: "تصویر محصول 15",
      product_id: 15,
      category_id: null,
      user_id: null,
      created_at: "2025-09-06T10:37:27.736Z",
      media: null,
    },
    brand: {
      id: 7,
      name: "ماگ‌لند",
      logo: "/images/brands/mugland.png",
    },
    category: {
      id: 33,
      title: "تسبیح سنگی",
      slug: "mohr-tasbih-sub3",
      level: 2,
      parent: {
        id: 3,
        title: "مهر و تسبیح",
        slug: "mohr-tasbih",
        level: 1,
        parent: null,
        parent_id: 3,
        discount: "15%",
      },
      parent_id: 3,
    },
    attribute_nodes: [],
    specifications: [],
    variants: [],
    count: 0,
    average_rating: 3.5,
    items: [],
  },
  {
    id: 16,
    name: "گردنبند نقره با پلاک الله",
    price: "704734",
    stock: 91,
    is_same_day_shipping: false,
    requires_preparation: false,
    preparation_days: null,
    is_limited_stock: false,
    discount_amount: "7257",
    discount_percent: 14,
    is_featured: true,
    weight: "0.54",
    weight_unit: "kg",
    description: "توضیحات تستی برای گردنبند نقره با پلاک الله",
    is_visible: true,
    order_limit: 5,
    category_id: 72,
    media_pinned_id: 1601,
    helper_id: null,
    helper: null,
    brand_id: 6,
    created_at: "2025-09-06T10:37:27.736Z",
    updated_at: "2025-09-06T10:37:27.736Z",
    medias: [
      {
        id: 1601,
        url: "/mock/image_28.jpg",
        type: "image",
        alt_text: "تصویر محصول 16",
        product_id: 16,
        category_id: null,
        user_id: null,
        created_at: "2025-09-06T10:37:27.736Z",
        media: null,
      },
      {
        id: 1602,
        url: "/mock/image_4.jpg",
        type: "image",
        alt_text: "تصویر بندانگشتی محصول 16",
        product_id: 16,
        category_id: null,
        user_id: null,
        created_at: "2025-09-06T10:37:27.736Z",
        media: null,
      },
    ],
    media_pinned: {
      id: 1601,
      url: "/mock/image_28.jpg",
      type: "image",
      alt_text: "تصویر محصول 16",
      product_id: 16,
      category_id: null,
      user_id: null,
      created_at: "2025-09-06T10:37:27.736Z",
      media: null,
    },
    brand: {
      id: 6,
      name: "دیجیتال‌پلاس",
      logo: "/images/brands/digitalplus.png",
    },
    category: {
      id: 72,
      title: "ریسه نوری",
      slug: "lighting-sub2",
      level: 2,
      parent: {
        id: 7,
        title: "روشنایی مذهبی",
        slug: "lighting",
        level: 1,
        parent: null,
        parent_id: 7,
        discount: "10%",
      },
      parent_id: 7,
    },
    attribute_nodes: [],
    specifications: [],
    variants: [],
    count: 0,
    average_rating: 3.5,
    items: [],
  },
  {
    id: 17,
    name: "تابلوی چوبی بسم‌الله الرحمن الرحیم",
    price: "378296",
    stock: 33,
    is_same_day_shipping: true,
    requires_preparation: true,
    preparation_days: null,
    is_limited_stock: false,
    discount_amount: "83645",
    discount_percent: 27,
    is_featured: false,
    weight: "1.85",
    weight_unit: "kg",
    description: "توضیحات تستی برای تابلوی چوبی بسم‌الله الرحمن الرحیم",
    is_visible: true,
    order_limit: 2,
    category_id: 12,
    media_pinned_id: 1701,
    helper_id: null,
    helper: null,
    brand_id: 1,
    created_at: "2025-09-06T10:37:27.736Z",
    updated_at: "2025-09-06T10:37:27.736Z",
    medias: [
      {
        id: 1701,
        url: "/mock/image_2.jpg",
        type: "image",
        alt_text: "تصویر محصول 17",
        product_id: 17,
        category_id: null,
        user_id: null,
        created_at: "2025-09-06T10:37:27.736Z",
        media: null,
      },
      {
        id: 1702,
        url: "/mock/image_18.jpg",
        type: "image",
        alt_text: "تصویر بندانگشتی محصول 17",
        product_id: 17,
        category_id: null,
        user_id: null,
        created_at: "2025-09-06T10:37:27.736Z",
        media: null,
      },
    ],
    media_pinned: {
      id: 1701,
      url: "/mock/image_2.jpg",
      type: "image",
      alt_text: "تصویر محصول 17",
      product_id: 17,
      category_id: null,
      user_id: null,
      created_at: "2025-09-06T10:37:27.736Z",
      media: null,
    },
    brand: {
      id: 1,
      name: "مهرآسا",
      logo: "/images/brands/mehrasa.png",
    },
    category: {
      id: 12,
      title: "ادعیه جیبی",
      slug: "prayers-books-sub2",
      level: 2,
      parent: {
        id: 1,
        title: "ادعیه و کتب مذهبی",
        slug: "prayers-books",
        level: 1,
        parent: null,
        parent_id: 1,
        discount: "10%",
      },
      parent_id: 1,
    },
    attribute_nodes: [],
    specifications: [],
    variants: [],
    count: 0,
    average_rating: 3.5,
    items: [],
  },
  {
    id: 18,
    name: "ست جانماز ترمه با مهر و تسبیح",
    price: "782807",
    stock: 12,
    is_same_day_shipping: true,
    requires_preparation: true,
    preparation_days: 4,
    is_limited_stock: false,
    discount_amount: "36931",
    discount_percent: 37,
    is_featured: false,
    weight: "1.84",
    weight_unit: "kg",
    description: "توضیحات تستی برای ست جانماز ترمه با مهر و تسبیح",
    is_visible: true,
    order_limit: 4,
    category_id: 51,
    media_pinned_id: 1801,
    helper_id: null,
    helper: null,
    brand_id: 3,
    created_at: "2025-09-06T10:37:27.736Z",
    updated_at: "2025-09-06T10:37:27.736Z",
    medias: [
      {
        id: 1801,
        url: "/mock/image_48.jpg",
        type: "image",
        alt_text: "تصویر محصول 18",
        product_id: 18,
        category_id: null,
        user_id: null,
        created_at: "2025-09-06T10:37:27.736Z",
        media: null,
      },
      {
        id: 1802,
        url: "/mock/image_9.jpg",
        type: "image",
        alt_text: "تصویر بندانگشتی محصول 18",
        product_id: 18,
        category_id: null,
        user_id: null,
        created_at: "2025-09-06T10:37:27.736Z",
        media: null,
      },
    ],
    media_pinned: {
      id: 1801,
      url: "/mock/image_48.jpg",
      type: "image",
      alt_text: "تصویر محصول 18",
      product_id: 18,
      category_id: null,
      user_id: null,
      created_at: "2025-09-06T10:37:27.736Z",
      media: null,
    },
    brand: {
      id: 3,
      name: "تسبیح‌کو",
      logo: "/images/brands/tasbihco.png",
    },
    category: {
      id: 51,
      title: "اسپیکر",
      slug: "digital-products-sub1",
      level: 2,
      parent: {
        id: 5,
        title: "محصولات دیجیتال",
        slug: "digital-products",
        level: 1,
        parent: null,
        parent_id: 5,
        discount: "0%",
      },
      parent_id: 5,
    },
    attribute_nodes: [],
    specifications: [],
    variants: [],
    count: 0,
    average_rating: 3.5,
    items: [],
  },
  {
    id: 19,
    name: "ساعت دیواری با طرح مسجدالنبی",
    price: "969881",
    stock: 80,
    is_same_day_shipping: true,
    requires_preparation: true,
    preparation_days: null,
    is_limited_stock: true,
    discount_amount: "97309",
    discount_percent: 22,
    is_featured: true,
    weight: "0.64",
    weight_unit: "kg",
    description: "توضیحات تستی برای ساعت دیواری با طرح مسجدالنبی",
    is_visible: true,
    order_limit: 3,
    category_id: 31,
    media_pinned_id: 1901,
    helper_id: null,
    helper: null,
    brand_id: 5,
    created_at: "2025-09-06T10:37:27.736Z",
    updated_at: "2025-09-06T10:37:27.736Z",
    medias: [
      {
        id: 1901,
        url: "/mock/image_10.jpg",
        type: "image",
        alt_text: "تصویر محصول 19",
        product_id: 19,
        category_id: null,
        user_id: null,
        created_at: "2025-09-06T10:37:27.736Z",
        media: null,
      },
      {
        id: 1902,
        url: "/mock/image_26.jpg",
        type: "image",
        alt_text: "تصویر بندانگشتی محصول 19",
        product_id: 19,
        category_id: null,
        user_id: null,
        created_at: "2025-09-06T10:37:27.736Z",
        media: null,
      },
    ],
    media_pinned: {
      id: 1901,
      url: "/mock/image_10.jpg",
      type: "image",
      alt_text: "تصویر محصول 19",
      product_id: 19,
      category_id: null,
      user_id: null,
      created_at: "2025-09-06T10:37:27.736Z",
      media: null,
    },
    brand: {
      id: 5,
      name: "چراغین",
      logo: "/images/brands/cheraghin.png",
    },
    category: {
      id: 31,
      title: "مهر",
      slug: "mohr-tasbih-sub1",
      level: 2,
      parent: {
        id: 3,
        title: "مهر و تسبیح",
        slug: "mohr-tasbih",
        level: 1,
        parent: null,
        parent_id: 3,
        discount: "15%",
      },
      parent_id: 3,
    },
    attribute_nodes: [],
    specifications: [],
    variants: [],
    count: 0,
    average_rating: 3.5,
    items: [],
  },
  {
    id: 20,
    name: "کتاب مفاتیح‌الجنان با جلد چرم",
    price: "992935",
    stock: 73,
    is_same_day_shipping: false,
    requires_preparation: true,
    preparation_days: null,
    is_limited_stock: false,
    discount_amount: "42601",
    discount_percent: 20,
    is_featured: false,
    weight: "0.10",
    weight_unit: "kg",
    description: "توضیحات تستی برای کتاب مفاتیح‌الجنان با جلد چرم",
    is_visible: true,
    order_limit: 5,
    category_id: 32,
    media_pinned_id: 2001,
    helper_id: null,
    helper: null,
    brand_id: 8,
    created_at: "2025-09-06T10:37:27.736Z",
    updated_at: "2025-09-06T10:37:27.736Z",
    medias: [
      {
        id: 2001,
        url: "/mock/image_52.jpg",
        type: "image",
        alt_text: "تصویر محصول 20",
        product_id: 20,
        category_id: null,
        user_id: null,
        created_at: "2025-09-06T10:37:27.736Z",
        media: null,
      },
      {
        id: 2002,
        url: "/mock/image_50.jpg",
        type: "image",
        alt_text: "تصویر بندانگشتی محصول 20",
        product_id: 20,
        category_id: null,
        user_id: null,
        created_at: "2025-09-06T10:37:27.736Z",
        media: null,
      },
    ],
    media_pinned: {
      id: 2001,
      url: "/mock/image_52.jpg",
      type: "image",
      alt_text: "تصویر محصول 20",
      product_id: 20,
      category_id: null,
      user_id: null,
      created_at: "2025-09-06T10:37:27.736Z",
      media: null,
    },
    brand: {
      id: 8,
      name: "اسپیکر‌استار",
      logo: "/images/brands/speakerstar.png",
    },
    category: {
      id: 32,
      title: "تسبیح چوبی",
      slug: "mohr-tasbih-sub2",
      level: 2,
      parent: {
        id: 3,
        title: "مهر و تسبیح",
        slug: "mohr-tasbih",
        level: 1,
        parent: null,
        parent_id: 3,
        discount: "15%",
      },
      parent_id: 3,
    },
    attribute_nodes: [],
    specifications: [],
    variants: [],
    count: 0,
    average_rating: 3.5,
    items: [],
  },
];

export const fakeProducts: Product[] = Array.from({ length: 20 }, (_, i) => {
  const id = i + 1;
  const now = new Date().toISOString();

  const brands = mockBrands;
  const productNames = [
    "قرآن‌کریم رقعی مخصوص حفظ",
    "سنگ نگین همراه تربت",
    "قرآن وزیری ترمو ترجمه کلمه به کلمه",
    "مصحف همراه (طلاکوب)",
    "تابلو مدرن دکوراتیو مذهبی",
    "تسبیح تایگر (چشم ببر)",
    "تسبیح عقیق شجر ترکیده سرخ",
    "استند رومیزی علی ولی الله",
    "نیم‌ست نقره طرح پروانه",
    "تسبیح فیروزه نیشابوری اصل",
    "قاب آیه‌الکرسی با خط نستعلیق",
    "جا قرآنی چوبی منبت‌کاری شده",
    "مهر تربت کربلا با قاب مخملی",
    "آویز ماشین با ذکر یا حسین",
    "شمع تزئینی با طرح اسماءالله",
    "گردنبند نقره با پلاک الله",
    "تابلوی چوبی بسم‌الله الرحمن الرحیم",
    "ست جانماز ترمه با مهر و تسبیح",
    "ساعت دیواری با طرح مسجدالنبی",
    "کتاب مفاتیح‌الجنان با جلد چرم",
  ];

  const parentCategory =
    categories[Math.floor(Math.random() * categories.length)];
  const category =
    parentCategory.children?.[
      Math.floor(Math.random() * parentCategory.children!.length)
    ];
  const brand = brands[Math.floor(Math.random() * brands.length)];

  const medias: Media[] = [
    {
      id: id * 100 + 1,
      url: `/mock/image_${Math.floor(Math.random() * 54)}.jpg`,
      type: "image",
      alt_text: `تصویر محصول ${id}`,
      product_id: id,
      category_id: null,
      user_id: null,
      created_at: now,
      media: null,
    },
    {
      id: id * 100 + 2,
      url: `/mock/image_${Math.floor(Math.random() * 54)}.jpg`,
      type: "image",
      alt_text: `تصویر بندانگشتی محصول ${id}`,
      product_id: id,
      category_id: null,
      user_id: null,
      created_at: now,
      media: null,
    },
  ];

  return {
    id,
    name: productNames[i % productNames.length],
    price: (Math.random() * 1000000).toFixed(0),
    stock: Math.floor(Math.random() * 100),
    is_same_day_shipping: Math.random() > 0.5,
    requires_preparation: Math.random() > 0.5,
    preparation_days:
      Math.random() > 0.5 ? Math.floor(Math.random() * 5) + 1 : null,
    is_limited_stock: Math.random() > 0.7,
    discount_amount: (Math.random() * 100000).toFixed(0),
    discount_percent: Math.floor(Math.random() * 50),
    is_featured: Math.random() > 0.5,
    weight: (Math.random() * 2).toFixed(2),
    weight_unit: "kg",
    description: `توضیحات تستی برای ${productNames[i % productNames.length]}`,
    is_visible: true,
    order_limit: Math.floor(Math.random() * 5) + 1,
    category_id: category!.id,
    media_pinned_id: medias[0].id,
    helper_id: null,
    helper: null,
    brand_id: brand.id,
    created_at: now,
    updated_at: now,
    medias,
    media_pinned: medias[0],
    brand,
    category: category!,
    attribute_nodes: [],
    specifications: [],
    variants: [],
    count: 0,
    average_rating: 3.5,
    items: [],
  };
});

export const addParentToCategores = (
  inputCategories: Category[],
  parent: Category | null
): Category[] => {
  return inputCategories.map((i) => {
    const addedParent = {
      ...i,
      parent: parent
        ? ({
            id: parent.id,
            title: parent.title,
            slug: parent.slug,
            level: parent?.level,
            parent: parent.parent,
            parent_id: parent.id,
            discount: parent.discount,
          } as Category)
        : null,
      parent_id: parent?.id ?? 0,
    };

    return {
      ...addedParent,
      children: addParentToCategores(i.children ?? [], addedParent),
    };
  });
};

export const addParentCategoryToProduct = () => {
  return products.map((i) => {
    const category = findCategory(i.category_id, categories);

    return { ...i, category };
  });
};

const findCategory = (
  category_id: number,
  categories: Category[]
): Partial<Category> | null => {
  const result = categories.map((c) => {
    const { children, ...cc } = c;

    return c.id === category_id
      ? cc
      : findCategory(category_id, children ?? []);
  });

  return result.find((i) => i) ?? null;
};
